[toolchain]
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
casino = "CasytXe4cEiXJEcE3yZKxJtaHTDpZFkrVoe7ChJqY8ma"

[programs.localnet]
casino = "AUqeYqxd7bAtrvyu7icRVgfLBa8i5jiS9QiHx6WfUhpf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
ledger = '.anchor\test-ledger'
rpc_port = 8899

[[test.validator.clone]]
address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"
